### ISSUE TITLE
Issue creating .cbor files

### ISSUE THREAD

**Issue by fedenanni** [TREMA-UNH/trec-car-release#1]
After creating a single .cbor file from a single xml I run this:
${bin}/trec-car-dump pages itwiki-20170801-pages-articles1.xml-p2p442893.cbor | less

And receive the following error message:

Failed to deserialise header of itwiki-20170801-pages-articles1.xml-p2p442893.cbor; provenance unavailable.
trec-car-dump: CborListHeaderDeserialiseError "itwiki-20170801-pages-articles1.xml-p2p442893.cbor" (DeserialiseFailure 0 "expected list start")

**Comment by laura-dietz** [comment]
This was with the latest commit on the multi-lingual branch

**Comment by laura-dietz** [comment]
@fedenanni  can you add the full path to the cbor file so Ben can reproduce the issue?

Can you also describe with which command the cbor was created?

**Comment by fedenanni** [comment]
path: ~/work/projects/LREC/trec-car-release/dumps.wikimedia.your.org/itwiki/20170801/release-v1.6/itwiki-20170801-pages-articles1.xml-p2p442893.bz2

**Comment by fedenanni** [comment]
I'm not sure if we used as a last command ./make.sh raw or something from Makefile
