### ISSUE TITLE
Error message running cabal new-build all

### ISSUE THREAD

**Issue by fedenanni** [TREMA-UNH/trec-car-release#2]
i just received this error message running "cabal new-build all"
cabal: Failed to build trec-car-tools-0.1.0.0 (which is required by
exe:trec-car-trec-run-filter from trec-car-tools-0.1.0.0,
exe:trec-car-transform-content from trec-car-tools-0.1.0.0 and others).

i'm in "fede/work/projects/LREC/mediawiki-annotate"

before doing that command I did:

git checkout
git checkout multi-lingual
git pull
git submodule update --recursive --init
cabal update

**Comment by bgamari** [comment]
Can you paste more of the error?

**Comment by fedenanni** [comment]
I re-ran it and this is the error that I get:

 - trec-car-filter-duplicates-0.1.0.0 (exe:trec-car-rewrite-duplicates) (dependency rebuilt)
 - trec-car-filter-duplicates-0.1.0.0 (exe:trec-car-minhash-duplicates) (dependency rebuilt)
 - trec-car-filter-duplicates-0.1.0.0 (exe:trec-car-find-duplicates) (dependency rebuilt)
 - trec-car-filter-duplicates-0.1.0.0 (exe:trec-car-duplicates-rewrite-table) (dependency rebuilt)
 - mediawiki-import-0.1.0.0 (exe:trec-car-import) (configuration changed)
Preprocessing library for trec-car-tools-0.1.0.0..
Building library for trec-car-tools-0.1.0.0..
[13 of 14] Compiling CAR.Retrieve     ( src/CAR/Retrieve.hs, /mnt/grapes/work/fede/projects/LREC/mediawiki-annotate/dist-newstyle/build/x86_64-linux/ghc-8.2.1/trec-car-tools-0.1.0.0/build/CAR/Retrieve.o )

src/CAR/Retrieve.hs:59:15: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at src/CAR/Retrieve.hs:25:1-18
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at src/CAR/Retrieve.hs:26:1-21
   |
59 |     mappend = (<>)
   |               ^^^^

src/CAR/Retrieve.hs:126:5: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Data.Monoid.<>’,
                             imported from ‘Data.Monoid’ at src/CAR/Retrieve.hs:25:1-18
                          or ‘Data.Semigroup.<>’,
                             imported from ‘Data.Semigroup’ at src/CAR/Retrieve.hs:26:1-21
    |
126 |     <> foldMap oneTerm queryTerms
    |     ^^
cabal: Failed to build trec-car-tools-0.1.0.0 (which is required by
exe:trec-car-trec-run-filter from trec-car-tools-0.1.0.0,
exe:trec-car-transform-content from trec-car-tools-0.1.0.0 and others).

**Comment by bgamari** [comment]
Sorry about that @fedenanni; this was my mistake. Try pulling and rebuilding.
